workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
stages:
  - lint
  - test-remote
  - test-self
  - docker_build
lint-checkout_repository:
  image: node:16
  stage: lint
  needs: []
  before_script:
    - git clone https://github.com/Tobiaskr12/SingularCI.git
    - cd SingularCI
  script:
    - npm install
    - npm run lint
test-remote-checkout_repository:
  image: node:16
  stage: test-remote
  needs:
    - lint-checkout_repository
  before_script:
    - git clone https://github.com/Tobiaskr12/SingularCI.git
    - cd SingularCI
  script:
    - npm install
    - npm run test
test-self-checkout_repository:
  image: node:16
  stage: test-self
  needs:
    - lint-checkout_repository
  before_script:
    - git clone https://github.com/Tobiaskr12/SingularCITestProject.git
    - cd SingularCITestProject
  script:
    - npm install
    - npm run test
docker_build-execute_docker_build:
  image: docker:latest
  stage: docker_build
  needs:
    - test-remote-checkout_repository
    - test-self-checkout_repository
  before_script: []
  script:
    - docker login -u saibotv2 -p $DOCKER_PASSWORD
    - docker build --pull -t "saibotv2/singularci-test" ./
    - docker push "saibotv2/singularci-test"
  services:
    - docker:dind



