workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
stages:
  - eslint_test
eslint_test-Checkout_repository:
  image: node:16
  stage: eslint_test
  script:
    - echo "Checkout task not supported for GitLab"
  needs: []
eslint_test-install_and_run_eslint:
  image: node:16
  stage: eslint_test
  script:
    - npm install -g eslint
    - eslint ./src
  needs: []
