workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
stages:
  - print
print-test_run_command:
  image: ubuntu:latest
  stage: print
  script:
    - echo "Run command executed successfully!"
  needs: []
