workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
stages:
  - lint
  - test
lint-checkout_repository:
  image: node:16
  stage: lint
  needs: []
  before_script:
    - git clone https://github.com/Tobiaskr12/SingularCITestProject.git
    - cd SingularCITestProject
  script:
    - npm install
    - npm run lint
test-checkout_repository:
  image: ubuntu:latest
  stage: test
  needs:
    - lint-checkout_repository
  before_script:
    - git clone https://github.com/Tobiaskr12/SingularCITestProject.git
    - cd SingularCITestProject
  script:
    - npm install
    - npm test
