pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: docker-username
      value: saibotv2

  triggers: 
    trigger_types:
      - push
    branches:
      - master
  
  stages:

    - stage:
        name: print
        runs_on: ubuntu-latest
        jobs:
          - name: test run command
            run: 
              - echo "Run command executed successfully!"
