pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: docker-username
      value: saibotv2

  triggers: 
    trigger_types:
      - push
    branches:
      - master
  
  stages:

    - stage:
        name: eslint_test
        runs_on: node:16
        jobs:
          - name: Checkout repository
            checkout: Tobiaskr12/SingularCITestProject
          - name: install and run eslint
            run: 
              - npm install -g eslint
              - eslint ./src
