pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: docker-username
      value: saibotv2

  triggers: 
    trigger_types:
      - push
    branches:
      - master
  
  stages:

    - stage:
        name: docker_build_test
        runs_on: ubuntu-latest
        jobs:
          - name: execute docker build
            docker_build:
              image_name: singular-ci-test-project
              docker_file_path: ./ 
              user_name: ${docker-username}
              password: ${secrets.DOCKER_PASSWORD}
