pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: test-variable
      value: test-value

  triggers: 
    trigger_types:
      - push
    branches:
      - master
  
  stages:

    - stage:
        name: lintstage
        runs_on: ubuntu-latest
        jobs:
          - name: execute run command
            run: 
              - echo "Run Command executed successfully"
