pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: docker-username
      value: saibotv2

  triggers: 
    trigger_types:
      - push
    branches:
      - master
  
  stages:

    - stage:
        name: test_stages_structure_1
        runs_on: ubuntu-latest
        jobs:
          - name: run_command_1
            run: 
              - echo "Run command 1 executed successfully" 
          - name: run_command_2
            run: 
              - echo "Run command 2 executed successfully" 
    
    - stage:
        name: test_stages_structure_2
        runs_on: ubuntu-latest
        needs: [test_stages_structure_1]
        jobs:
          - name: run_command_3
            run: 
              - echo "Run command 3 executed successfully" 
