on:
  push:
    branches:
      - master
jobs:
  docker_build_test:
    steps:
      - uses: djbender/docker-buildx-pull-or-build@v0.5
        with:
          docker_username: saibotv2
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./
          image: singular-ci-test-project
    runs-on: ubuntu-latest
