on:
  push:
    branches:
      - master
jobs:
  eslint_test:
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Tobiaskr12/SingularCITestProject
      - run: |
          npm install -g eslint
          eslint ./src
    runs-on: ubuntu-latest
    container: node:16
