on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  lint:
    steps:
      - run: git clone https://github.com/Tobiaskr12/SingularCITestProject.git
      - run: cd SingularCITestProject
      - run: npm install
      - run: npm run lint
    runs-on: ubuntu-latest
    container: node:16
  test:
    steps:
      - run: git clone https://github.com/Tobiaskr12/SingularCITestProject.git
      - run: cd SingularCITestProject
      - run: npm install
      - run: npm test
    runs-on: ubuntu-latest
    container: node:16
    needs:
      - lint
