on:
  push:
    branches:
      - master
jobs:
  test_stages_structure_1:
    steps:
      - run: echo "Run command 1 executed successfully"
      - run: echo "Run command 2 executed successfully"
    runs-on: ubuntu-latest
  test_stages_structure_2:
    steps:
      - run: echo "Run command 3 executed successfully"
    runs-on: ubuntu-latest
    needs:
      - test_stages_structure_1
