on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  lint:
    steps:
      - run: git clone https://github.com/Tobiaskr12/SingularCI.git
      - run: |
          npm install
          npm run lint
        working-directory: SingularCI
    runs-on: ubuntu-latest
    container: node:16
  test-remote:
    steps:
      - run: git clone https://github.com/Tobiaskr12/SingularCI.git
      - run: |
          npm install
          npm run test
        working-directory: SingularCI
    runs-on: ubuntu-latest
    container: node:16
    needs:
      - lint
  test-self:
    steps:
      - run: git clone https://github.com/Tobiaskr12/SingularCITestProject.git
      - run: |
          npm install
          npm run test
        working-directory: SingularCITestProject
    runs-on: ubuntu-latest
    container: node:16
    needs:
      - lint
      - test-remote
